- name: Create setup directory
  win_file:
    path: "{{ working_path }}"
    state: directory

- name: Copy config file
  win_copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ working_path }}"
  loop:
    - preset.txt
    - Win10.ps1

- name: Set show hidden files/folders and file extensions for the default user profile
  win_regedit:
    path: HKLM:\ANSIBLE\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    type: dword
    state: present
    hive: C:\Users\Default\NTUSER.dat
  loop:
    - name: Hidden
      data: 1
    - name: HideFileExt
      data: 0
